name: ci

env:
  SERVICE_NAME: flaskpytestgitlabcd
  RUN_REGION: europe-west1

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    name: Deploy to CloudRun
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: ${{ env.SERVICE_NAME }}:latest

      - name: Inspect
        run: |
          docker image inspect ${{ env.SERVICE_NAME }}:latest

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCR_JSON_KEY }}'
        export_default_credentials: true
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: Deploy to CloudRun
      run: |-
        gcloud run deploy "$SERVICE_NAME" \
         --quiet \
         --image "eu.gcr.io/my-project/$SERVICE_NAME:$GITHUB_SHA" \
         --region "$RUN_REGION" \
         --platform "managed" \
         --allow-unauthenticated \
         --memory=512Mi