name: ci

env:
  SERVICE_NAME: flaskpytestgitlabcd
  RUN_REGION: europe-west1
  GCP_PROJECT_ID: stoikman-198318

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    name: Deploy to CloudRun
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}:latest

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCR_JSON_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: 'Set docker registry to gcloud'
        run: 'gcloud auth configure-docker -q'

      - name: 'Push image to Google Container Registry'
        run: 'docker push gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}:latest'

      - name: 'Deploy to Google Cloud Run'
        run: |-
          gcloud run deploy "${{ env.SERVICE_NAME }}" \
                      --quiet \
                      --image "gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}:latest" \
                      --region "$RUN_REGION" \
                      --platform "managed" \
                      --allow-unauthenticated \
                      --memory=512Mi
