name: ci

env:
  SERVICE_NAME: flaskpytestgitlabcd
  RUN_REGION: europe-west1
  GCP_PROJECT_ID: stoikman-198318

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    name: Deploy to CloudRun
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Minify
        run: |
            wget https://downloads.dockerslim.com/releases/1.37.3/dist_linux.tar.gz
            tar zxvf dist_linux.tar.gz
            chmod +x ./dist_linux/docker-slim
            ./dist_linux/docker-slim build --tag gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}-slim:latest "gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}:latest"

      - name: Inspect
        run: |
            docker image inspect gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}-slim:latest

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCR_JSON_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: 'Set docker registry to gcloud'
        run: 'gcloud auth configure-docker -q'

      - name: 'Push image to Google Container Registry'
        run: 'docker push gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}-slim:latest'

      - name: 'Deploy to Google Cloud Run'
        run: |-
          gcloud run deploy "${{ env.SERVICE_NAME }}" \
                      --quiet \
                      --image "gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}-slim:latest" \
                      --region "$RUN_REGION" \
                      --platform "managed" \
                      --allow-unauthenticated \
                      --memory=512Mi
